### ISSUE TITLE
Fails to Build

### ISSUE THREAD

**Issue by PibePlayer** [airesnoronha/wuxiacraft#8]
Currently on arm64 Ubuntu 18.04 with openjdk-8 and openjfx installed... This is the output of gradlew build:

`root@localhost:~/wuxiacraft# ./gradlew build                                To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################                                    ForgeGradle 2.3-SNAPSHOT-6084129e
  https://github.com/MinecraftForge/ForgeGradle                             #################################################
                 Powered by MCP                                                          http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX                                          Fesh0r, IngisKahn, bspkrs, LexManos
#################################################                           :deobfCompileDummyTask
:getVersionJson                                                             :extractUserdev
:downloadClient SKIPPED                                                     :downloadServer SKIPPED
:splitServerJar SKIPPED                                                     :mergeJars SKIPPED
:applyBinaryPatches SKIPPED                                                 :deobfProvidedDummyTask
:extractDependencyATs SKIPPED                                               :extractMcpData SKIPPED
:extractMcpMappings SKIPPED                                                 :genSrgs SKIPPED
:deobfMcMCP SKIPPED                                                         :sourceApiJava
:compileApiJava UP-TO-DATE                                                  :processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE                                                      :sourceMainJava
:compileJava/root/wuxiacraft/build/sources/main/java/com/airesnor/wuxiacraft/entities/tileentity/CauldronTileEntity.java:5: error: cannot find symbol
import com.airesnor.wuxiacraft.profession.alchemy.Recipes;                                                                   ^                            symbol:   class Recipes                                                     location: package com.airesnor.wuxiacraft.profession.alchemy              /root/wuxiacraft/build/sources/main/java/com/airesnor/wuxiacraft/commands/CreateRecipeCommand.java:6: error: cannot find symbol
import com.airesnor.wuxiacraft.profession.alchemy.Recipes;                                                                   ^                            symbol:   class Recipes                                                     location: package com.airesnor.wuxiacraft.profession.alchemy
/root/wuxiacraft/build/sources/main/java/com/airesnor/wuxiacraft/handlers/RendererHandler.java:18: error: package javafx.animation does not exist       import javafx.animation.Interpolator;                                                              ^
/root/wuxiacraft/build/sources/main/java/com/airesnor/wuxiacraft/items/ItemRecipe.java:6: error: cannot find symbol                                     import com.airesnor.wuxiacraft.profession.alchemy.Recipes;                                                                   ^                            symbol:   class Recipes                                                     location: package com.airesnor.wuxiacraft.profession.alchemy              4 errors                                                                     FAILED
                                                                            FAILURE: Build failed with an exception.                                                                                                                * What went wrong:                                                          Execution failed for task ':compileJava'.                                   > Compilation failed; see the compiler error output for details.                                                                                        * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.                                                                                                                      BUILD FAILED
                                                                            Total time: 3 mins 12.636 secs
`

**Comment by airesnoronha** [comment]
This is because Recipes was private till that version.
